/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package antarmuka;

import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import kontrol.GmiController;
import kontrol.LvqController;
import kontrol.VerificationController;



/**
 *
 * @author unsri-ict
 */
public class FormVerification extends javax.swing.JFrame {
    int numberofinput ; 
    int numberofcluster;
    int inputdimension = 7; 
    GmiController gc = new GmiController();
    VerificationController vc = new VerificationController();
    double[][] M = new double[8][7];
    
    
   
    /**
     * Creates new form FormTraining
     */
    public FormVerification() {
        initComponents();
        setTitle("Verifikasi");
        setLocationRelativeTo(null);
        //jButtonLoadImage1.setEnabled(false);
        //jTabbedPane3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelVerification = new javax.swing.JPanel();
        jPanelSignature = new javax.swing.JPanel();
        jLabelSignature = new javax.swing.JLabel();
        jPanelSignature7 = new javax.swing.JPanel();
        jLabelVerificationResult = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelSignature1 = new javax.swing.JPanel();
        jLabelSignature1 = new javax.swing.JLabel();
        jPanelSignature8 = new javax.swing.JPanel();
        jLabelVerificationResult1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelSignature9 = new javax.swing.JPanel();
        jLabelVerificationResult3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelSignature3 = new javax.swing.JPanel();
        jLabelSignature3 = new javax.swing.JLabel();
        jPanelSignature4 = new javax.swing.JPanel();
        jLabelSignature4 = new javax.swing.JLabel();
        jPanelSignature10 = new javax.swing.JPanel();
        jLabelVerificationResult4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelSignature5 = new javax.swing.JPanel();
        jLabelSignature5 = new javax.swing.JLabel();
        jPanelSignature11 = new javax.swing.JPanel();
        jLabelVerificationResult5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelSignature6 = new javax.swing.JPanel();
        jLabelSignature6 = new javax.swing.JLabel();
        jPanelSignature12 = new javax.swing.JPanel();
        jLabelVerificationResult6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelSignature13 = new javax.swing.JPanel();
        jLabelSignature7 = new javax.swing.JLabel();
        jPanelSignature14 = new javax.swing.JPanel();
        jLabelVerificationResult7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelSignature15 = new javax.swing.JPanel();
        jLabelVerificationResult8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelSignature16 = new javax.swing.JPanel();
        jLabelSignature8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonChoose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        numberofsignatures = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldnumofcluster = new javax.swing.JTextField();
        jTextFieldtarget = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonVerification1 = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelVerification.setBackground(new java.awt.Color(204, 204, 204));
        jPanelVerification.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelSignature.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature.setBorder(javax.swing.BorderFactory.createTitledBorder("1"));

        javax.swing.GroupLayout jPanelSignatureLayout = new javax.swing.GroupLayout(jPanelSignature);
        jPanelSignature.setLayout(jPanelSignatureLayout);
        jPanelSignatureLayout.setHorizontalGroup(
            jPanelSignatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignatureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignatureLayout.setVerticalGroup(
            jPanelSignatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignatureLayout.createSequentialGroup()
                .addComponent(jLabelSignature, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature7.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature7Layout = new javax.swing.GroupLayout(jPanelSignature7);
        jPanelSignature7.setLayout(jPanelSignature7Layout);
        jPanelSignature7Layout.setHorizontalGroup(
            jPanelSignature7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature7Layout.setVerticalGroup(
            jPanelSignature7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature7Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature1.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature1.setBorder(javax.swing.BorderFactory.createTitledBorder("2"));

        javax.swing.GroupLayout jPanelSignature1Layout = new javax.swing.GroupLayout(jPanelSignature1);
        jPanelSignature1.setLayout(jPanelSignature1Layout);
        jPanelSignature1Layout.setHorizontalGroup(
            jPanelSignature1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature1Layout.setVerticalGroup(
            jPanelSignature1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature1Layout.createSequentialGroup()
                .addComponent(jLabelSignature1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature8.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature8.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature8Layout = new javax.swing.GroupLayout(jPanelSignature8);
        jPanelSignature8.setLayout(jPanelSignature8Layout);
        jPanelSignature8Layout.setHorizontalGroup(
            jPanelSignature8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature8Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature8Layout.setVerticalGroup(
            jPanelSignature8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature8Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature9.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature9.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature9Layout = new javax.swing.GroupLayout(jPanelSignature9);
        jPanelSignature9.setLayout(jPanelSignature9Layout);
        jPanelSignature9Layout.setHorizontalGroup(
            jPanelSignature9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature9Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature9Layout.setVerticalGroup(
            jPanelSignature9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature9Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature3.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature3.setBorder(javax.swing.BorderFactory.createTitledBorder("3"));

        javax.swing.GroupLayout jPanelSignature3Layout = new javax.swing.GroupLayout(jPanelSignature3);
        jPanelSignature3.setLayout(jPanelSignature3Layout);
        jPanelSignature3Layout.setHorizontalGroup(
            jPanelSignature3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature3Layout.setVerticalGroup(
            jPanelSignature3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature3Layout.createSequentialGroup()
                .addComponent(jLabelSignature3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature4.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature4.setBorder(javax.swing.BorderFactory.createTitledBorder("4"));

        javax.swing.GroupLayout jPanelSignature4Layout = new javax.swing.GroupLayout(jPanelSignature4);
        jPanelSignature4.setLayout(jPanelSignature4Layout);
        jPanelSignature4Layout.setHorizontalGroup(
            jPanelSignature4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature4Layout.setVerticalGroup(
            jPanelSignature4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature4Layout.createSequentialGroup()
                .addComponent(jLabelSignature4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature10.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature10.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature10Layout = new javax.swing.GroupLayout(jPanelSignature10);
        jPanelSignature10.setLayout(jPanelSignature10Layout);
        jPanelSignature10Layout.setHorizontalGroup(
            jPanelSignature10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature10Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature10Layout.setVerticalGroup(
            jPanelSignature10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature10Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature5.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature5.setBorder(javax.swing.BorderFactory.createTitledBorder("5"));

        javax.swing.GroupLayout jPanelSignature5Layout = new javax.swing.GroupLayout(jPanelSignature5);
        jPanelSignature5.setLayout(jPanelSignature5Layout);
        jPanelSignature5Layout.setHorizontalGroup(
            jPanelSignature5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature5Layout.setVerticalGroup(
            jPanelSignature5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature5Layout.createSequentialGroup()
                .addComponent(jLabelSignature5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature11.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature11.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature11Layout = new javax.swing.GroupLayout(jPanelSignature11);
        jPanelSignature11.setLayout(jPanelSignature11Layout);
        jPanelSignature11Layout.setHorizontalGroup(
            jPanelSignature11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature11Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature11Layout.setVerticalGroup(
            jPanelSignature11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature11Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature6.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature6.setBorder(javax.swing.BorderFactory.createTitledBorder("6"));

        javax.swing.GroupLayout jPanelSignature6Layout = new javax.swing.GroupLayout(jPanelSignature6);
        jPanelSignature6.setLayout(jPanelSignature6Layout);
        jPanelSignature6Layout.setHorizontalGroup(
            jPanelSignature6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature6Layout.setVerticalGroup(
            jPanelSignature6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature6Layout.createSequentialGroup()
                .addComponent(jLabelSignature6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature12.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature12.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature12Layout = new javax.swing.GroupLayout(jPanelSignature12);
        jPanelSignature12.setLayout(jPanelSignature12Layout);
        jPanelSignature12Layout.setHorizontalGroup(
            jPanelSignature12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature12Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature12Layout.setVerticalGroup(
            jPanelSignature12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature12Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature13.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature13.setBorder(javax.swing.BorderFactory.createTitledBorder("7"));

        javax.swing.GroupLayout jPanelSignature13Layout = new javax.swing.GroupLayout(jPanelSignature13);
        jPanelSignature13.setLayout(jPanelSignature13Layout);
        jPanelSignature13Layout.setHorizontalGroup(
            jPanelSignature13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature13Layout.setVerticalGroup(
            jPanelSignature13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature13Layout.createSequentialGroup()
                .addComponent(jLabelSignature7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanelSignature14.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature14.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature14Layout = new javax.swing.GroupLayout(jPanelSignature14);
        jPanelSignature14.setLayout(jPanelSignature14Layout);
        jPanelSignature14Layout.setHorizontalGroup(
            jPanelSignature14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature14Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature14Layout.setVerticalGroup(
            jPanelSignature14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature14Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature15.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature15.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil"));

        jLabelVerificationResult8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/drawing_pen1.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSignature15Layout = new javax.swing.GroupLayout(jPanelSignature15);
        jPanelSignature15.setLayout(jPanelSignature15Layout);
        jPanelSignature15Layout.setHorizontalGroup(
            jPanelSignature15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignature15Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVerificationResult8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature15Layout.setVerticalGroup(
            jPanelSignature15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSignature15Layout.createSequentialGroup()
                .addComponent(jLabelVerificationResult8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSignature16.setBackground(new java.awt.Color(204, 204, 204));
        jPanelSignature16.setBorder(javax.swing.BorderFactory.createTitledBorder("8"));

        javax.swing.GroupLayout jPanelSignature16Layout = new javax.swing.GroupLayout(jPanelSignature16);
        jPanelSignature16.setLayout(jPanelSignature16Layout);
        jPanelSignature16Layout.setHorizontalGroup(
            jPanelSignature16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSignature8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSignature16Layout.setVerticalGroup(
            jPanelSignature16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignature16Layout.createSequentialGroup()
                .addComponent(jLabelSignature8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelVerificationLayout = new javax.swing.GroupLayout(jPanelVerification);
        jPanelVerification.setLayout(jPanelVerificationLayout);
        jPanelVerificationLayout.setHorizontalGroup(
            jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerificationLayout.createSequentialGroup()
                .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSignature7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanelSignature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSignature11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelVerificationLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanelSignature5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSignature8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSignature12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSignature1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSignature6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSignature9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSignature14, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSignature3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelSignature13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelVerificationLayout.createSequentialGroup()
                            .addComponent(jPanelSignature15, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22))
                        .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerificationLayout.createSequentialGroup()
                                .addComponent(jPanelSignature10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerificationLayout.createSequentialGroup()
                                .addComponent(jPanelSignature4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanelVerificationLayout.setVerticalGroup(
            jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSignature7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSignature8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSignature9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSignature10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelVerificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelVerificationLayout.createSequentialGroup()
                            .addComponent(jPanelSignature5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelSignature11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelVerificationLayout.createSequentialGroup()
                            .addComponent(jPanelSignature6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanelSignature12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSignature14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerificationLayout.createSequentialGroup()
                        .addComponent(jPanelSignature16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSignature15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Verification", jPanelVerification);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));

        jLabel6.setText("Id Nama ");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jButtonChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/photography.png"))); // NOI18N
        jButtonChoose.setText("Unggah Tanda Tangan");
        jButtonChoose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonChoose.setBorderPainted(false);
        jButtonChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah Tanda Tangan");

        numberofsignatures.setText("8");
        numberofsignatures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofsignaturesActionPerformed(evt);
            }
        });

        jLabel8.setText("Jumlah Klasifikasi");

        jTextFieldnumofcluster.setText("20");
        jTextFieldnumofcluster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumofclusterActionPerformed(evt);
            }
        });

        jTextFieldtarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtargetActionPerformed(evt);
            }
        });

        jLabel9.setText("Target");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numberofsignatures, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldnumofcluster, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldtarget, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldtarget))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(numberofsignatures)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldnumofcluster))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonVerification1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id_card.png"))); // NOI18N
        jButtonVerification1.setText("Verifikasi");
        jButtonVerification1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonVerification1.setBorderPainted(false);
        jButtonVerification1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerification1ActionPerformed(evt);
            }
        });

        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove.png"))); // NOI18N
        jButtonReset.setText("Hapus");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        jButtonBack.setText("Kembali");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerification1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReset))
                    .addComponent(jTabbedPane2))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVerification1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonReset))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseActionPerformed
        // TODO add your handling code here:
        String id = jTextFieldId.getText();
       
        numberofinput = Integer.parseInt(numberofsignatures.getText());
        ImageIcon[]icon = new ImageIcon[numberofinput];
        File []file = new File[numberofinput];
        String path = null;
        String result = null;
        
        
        
        if(id.equals("")){
            JOptionPane.showMessageDialog(null, "Lengkapi Id Nama", "Pesan Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            JFileChooser jfc = new JFileChooser("data");
            jfc.setMultiSelectionEnabled(true);
            jfc.setFileFilter(new FileNameExtensionFilter("file (*.png)","png"));
            jfc.setDialogTitle("Choose Signatures");
            int r = jfc.showOpenDialog(this);
        
            if(r==JFileChooser.APPROVE_OPTION){
                try{
                    file = jfc.getSelectedFiles();
                    for(int i=0;i<file.length;i++){
                    icon[i] = new ImageIcon(file[i].getPath());
                    jLabelSignature.setIcon(icon[0]);
                    jLabelSignature1.setIcon(icon[1]);
                    jLabelSignature3.setIcon(icon[2]);
                    jLabelSignature4.setIcon(icon[3]);
                    jLabelSignature5.setIcon(icon[4]);
                    jLabelSignature6.setIcon(icon[5]);
                    jLabelSignature7.setIcon(icon[6]);
                    jLabelSignature8.setIcon(icon[7]);
                    gc.setFile(file[i]);
                    M[i]=gc.MomentInvarint();
                    }
                    
                }
                catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Unggah Tanda Tangan Gagal : " + ex.getMessage(),"Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
               }
            }
       }
       
    }//GEN-LAST:event_jButtonChooseActionPerformed

    private void jButtonVerification1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerification1ActionPerformed
        // TODO add your handling code here:
         String id = jTextFieldId.getText();
         numberofinput= Integer.parseInt(numberofsignatures.getText());
         String t = vc.GetTarget(id);
         jTextFieldtarget.setText(t);
         numberofcluster = Integer.parseInt(jTextFieldnumofcluster.getText());
         String target =jTextFieldtarget.getText();
         String hasil[]=new String[8];
         
         for(int p = 0; p<numberofinput; p++){
             String[]s = new String[3];
             s[0] = numberofsignatures.getText();
             s[1] = jTextFieldnumofcluster.getText();
             s[2] = jTextFieldtarget.getText();
             
             vc.SetDataUser(s);
             vc.DefineParameters();
             
             double []m = new double[numberofcluster*inputdimension];
             double[][] w = new double[numberofcluster][inputdimension];
             vc.SetInputVector(M[p]);
             
             
             m=vc.GetWeights(id);
             int count = 0;
             for(int i=0;i<numberofcluster;i++){
                 for(int j=0;j<inputdimension;j++){
                     w[i][j]=m[count];
                     count++;
                 }
                 
             }
             vc.SetWeights(w);
             vc.MappingInputVector(); 
             hasil[p]=vc.Verification();
             
             jLabelVerificationResult.setText(hasil[0]);
             jLabelVerificationResult1.setText(hasil[1]);
             jLabelVerificationResult3.setText(hasil[2]);
             jLabelVerificationResult4.setText(hasil[3]);
             jLabelVerificationResult5.setText(hasil[4]);
             jLabelVerificationResult6.setText(hasil[5]);
             jLabelVerificationResult7.setText(hasil[6]);
             jLabelVerificationResult8.setText(hasil[7]);
         }      
    }//GEN-LAST:event_jButtonVerification1ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new FormMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldId.setText(null);
        jLabelSignature.setIcon(null);
        jLabelSignature1.setIcon(null);
        jLabelSignature3.setIcon(null);
        jLabelSignature4.setIcon(null);
        jLabelSignature5.setIcon(null);
        jLabelSignature6.setIcon(null);
        jLabelSignature7.setIcon(null);
        jLabelSignature8.setIcon(null);
        jTextFieldtarget.setText(null);
        jLabelVerificationResult.setText(null);
        jLabelVerificationResult1.setText(null);
        jLabelVerificationResult3.setText(null);
        jLabelVerificationResult4.setText(null);
        jLabelVerificationResult5.setText(null);
        jLabelVerificationResult6.setText(null);
        jLabelVerificationResult7.setText(null);
        jLabelVerificationResult8.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void numberofsignaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofsignaturesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofsignaturesActionPerformed

    private void jTextFieldnumofclusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumofclusterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumofclusterActionPerformed

    private void jTextFieldtargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtargetActionPerformed

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormVerification().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChoose;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonVerification1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSignature;
    private javax.swing.JLabel jLabelSignature1;
    private javax.swing.JLabel jLabelSignature3;
    private javax.swing.JLabel jLabelSignature4;
    private javax.swing.JLabel jLabelSignature5;
    private javax.swing.JLabel jLabelSignature6;
    private javax.swing.JLabel jLabelSignature7;
    private javax.swing.JLabel jLabelSignature8;
    private javax.swing.JLabel jLabelVerificationResult;
    private javax.swing.JLabel jLabelVerificationResult1;
    private javax.swing.JLabel jLabelVerificationResult3;
    private javax.swing.JLabel jLabelVerificationResult4;
    private javax.swing.JLabel jLabelVerificationResult5;
    private javax.swing.JLabel jLabelVerificationResult6;
    private javax.swing.JLabel jLabelVerificationResult7;
    private javax.swing.JLabel jLabelVerificationResult8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelSignature;
    private javax.swing.JPanel jPanelSignature1;
    private javax.swing.JPanel jPanelSignature10;
    private javax.swing.JPanel jPanelSignature11;
    private javax.swing.JPanel jPanelSignature12;
    private javax.swing.JPanel jPanelSignature13;
    private javax.swing.JPanel jPanelSignature14;
    private javax.swing.JPanel jPanelSignature15;
    private javax.swing.JPanel jPanelSignature16;
    private javax.swing.JPanel jPanelSignature3;
    private javax.swing.JPanel jPanelSignature4;
    private javax.swing.JPanel jPanelSignature5;
    private javax.swing.JPanel jPanelSignature6;
    private javax.swing.JPanel jPanelSignature7;
    private javax.swing.JPanel jPanelSignature8;
    private javax.swing.JPanel jPanelSignature9;
    private javax.swing.JPanel jPanelVerification;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldnumofcluster;
    private javax.swing.JTextField jTextFieldtarget;
    private javax.swing.JTextField numberofsignatures;
    // End of variables declaration//GEN-END:variables

    
}
